# url: "http://companyinc.company/"
url: "http://localhost:4000/"
title: Company Inc.&reg;&trade;&copy;
description: "A stealth mode startup excited about our #brand. Connect with our worldwide market using #companyinc"
permalink: /:year/:month/:day/:title

about: >
  Company Inc. is a stealth mode startup that answers a greater calling. Our group sees the world in a different light and is prepared to play a pivotal role in disrupting the new age market. We are delighted with our unique product and eagerly anticipate the grand reveal. We consider ourselves #blessed to have the opportunity to grow our brand in this exciting age of explosive innovation and look forward to receiving seed money to further our objective. Meet our diverse Founding Board of Officers below and learn how we mesh together like gears in a well-oiled machine!

# GitHub Gems
gems:
  - jekyll-feed
